### Ćwiczenie 2


#### -  braki danych:

1. Zbadaj braki danych:
- stwórz maskę logiczną
- sprawdź nulle i sume nulli dla wszystkich kolumn
- sprawdź udział procentowy nullów.

2. Uzupełnij braki za pomocą sklearn:
- mean - zmienna 'weight'
- median - zmienna 'price
- most frequent, constant - zmienne kategoryczne

3. Uzupełnij braki przy pomocy pandas fillna/dropna

4. Usuń wiersze zawierające NaN, więcej niz 2 Nan, wytnij wiersze z NaN, wytnij wiersze bez NaN



#### - brak idanych w szeregach czasowych

1. Jakie mamy możliwości uzupełniania danych w szeregach czasowych ?
2. Co to jest interpolacja?
3. Stwórz dataframe na podstawie danych - data = {'price': [108, 109, 110, 110, 109, np.nan, np.nan, 112, 111, 111]}
- jako index dodaj szereg czasowy odpowiednią funkcją pandas, zaczynając od godziny 9:00 np. 2020-01-01

4. Stwórz wiualizacje za pomocą plotly.express

5. Uzupełnij braki - usuń NaN, wypełnij 0, median, mean, ffill, bfill

6. Która metoda wydaje się być najlepsza ?

In [3]:
data = {
    'size': ['XL', 'L', 'M', np.nan, 'M', 'M'],
    'color': ['red', 'green', 'blue', 'green', 'red', 'green'],
    'gender': ['female', 'male', np.nan, 'female', 'female', 'male'],
    'price': [199.0, 89.0, np.nan, 129.0, 79.0, 89.0],
    'weight': [500, 450, 300, np.nan, 410, np.nan],
    'bought': ['yes', 'no', 'yes', 'no', 'yes', 'no']
}

df_raw = pd.DataFrame(data=data)
df_raw

  size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue     NaN    NaN   300.0    yes
3  NaN  green  female  129.0     NaN     no
4    M    red  female   79.0   410.0    yes
5    M  green    male   89.0     NaN     no